/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package programa;

import javax.swing.JOptionPane;

/**
 *
 * @author Equip
 */
public class frmMenus extends javax.swing.JFrame {

    /**
     * Creates new form frmMenus
     */
    public frmMenus() {
        initComponents();
        this.setLocationRelativeTo(this);   //situado al centro
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menucontextual = new javax.swing.JPopupMenu();
        mnuApagarT1 = new javax.swing.JMenuItem();
        mnuEncenderT1 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        mnuTodasD1 = new javax.swing.JMenuItem();
        mnuTodasN1 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        mnuPrincipales1 = new javax.swing.JMenuItem();
        mnuSecudarias1 = new javax.swing.JMenuItem();
        mnuSeguridad1 = new javax.swing.JMenuItem();
        pnOficina1 = new javax.swing.JPanel();
        chkLuzPrincipal1 = new javax.swing.JCheckBox();
        chkLuzSecundaria1 = new javax.swing.JCheckBox();
        chkLuzSeguridad1 = new javax.swing.JCheckBox();
        luz131 = new javax.swing.JLabel();
        luz132 = new javax.swing.JLabel();
        luz111 = new javax.swing.JLabel();
        luz112 = new javax.swing.JLabel();
        luz121 = new javax.swing.JLabel();
        luz122 = new javax.swing.JLabel();
        pnOficina2 = new javax.swing.JPanel();
        chkLuzPrincipal2 = new javax.swing.JCheckBox();
        chkLuzSecundaria2 = new javax.swing.JCheckBox();
        chkLuzSeguridad2 = new javax.swing.JCheckBox();
        luz211 = new javax.swing.JLabel();
        luz212 = new javax.swing.JLabel();
        luz221 = new javax.swing.JLabel();
        luz231 = new javax.swing.JLabel();
        luz232 = new javax.swing.JLabel();
        luz222 = new javax.swing.JLabel();
        pnOficina3 = new javax.swing.JPanel();
        chkLuzPrincipal3 = new javax.swing.JCheckBox();
        chkLuzSecundaria3 = new javax.swing.JCheckBox();
        chkLuzSeguridad3 = new javax.swing.JCheckBox();
        luz321 = new javax.swing.JLabel();
        luz311 = new javax.swing.JLabel();
        luz312 = new javax.swing.JLabel();
        luz322 = new javax.swing.JLabel();
        luz331 = new javax.swing.JLabel();
        luz332 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        bapagartodas = new javax.swing.JButton();
        bencendertodas = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        bdia = new javax.swing.JButton();
        bnoche = new javax.swing.JButton();
        bdiaicono = new javax.swing.JButton();
        bnocheicono = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        binfoprincipales = new javax.swing.JButton();
        binfosecundarias = new javax.swing.JButton();
        binfoseguridad = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        mnuBarraMenus = new javax.swing.JMenuBar();
        mnuActivación = new javax.swing.JMenu();
        mnuApagarT = new javax.swing.JMenuItem();
        mnuEncenderT = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuDia = new javax.swing.JMenu();
        mnuOfD1 = new javax.swing.JMenuItem();
        mnuOfD2 = new javax.swing.JMenuItem();
        mnuOfD3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuTodasD = new javax.swing.JMenuItem();
        mnuNoche = new javax.swing.JMenu();
        mnuOfN1 = new javax.swing.JMenuItem();
        mnuOfN2 = new javax.swing.JMenuItem();
        mnuOfN3 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuTodasN = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuSalir = new javax.swing.JMenuItem();
        mnuInfo = new javax.swing.JMenu();
        mnuPrincipales = new javax.swing.JMenuItem();
        mnuSecudarias = new javax.swing.JMenuItem();
        mnuSeguridad = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnuAcerca = new javax.swing.JMenuItem();

        menucontextual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menucontextualMouseClicked(evt);
            }
        });

        mnuApagarT1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnuApagarT1.setText("Apagar Todas");
        mnuApagarT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuApagarT1ActionPerformed(evt);
            }
        });
        menucontextual.add(mnuApagarT1);

        mnuEncenderT1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mnuEncenderT1.setText("Encender Todas");
        mnuEncenderT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEncenderT1ActionPerformed(evt);
            }
        });
        menucontextual.add(mnuEncenderT1);
        menucontextual.add(jSeparator9);

        mnuTodasD1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        mnuTodasD1.setText("Modo Dia");
        mnuTodasD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTodasD1ActionPerformed(evt);
            }
        });
        menucontextual.add(mnuTodasD1);

        mnuTodasN1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mnuTodasN1.setText("Modo Noche");
        mnuTodasN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTodasN1ActionPerformed(evt);
            }
        });
        menucontextual.add(mnuTodasN1);
        menucontextual.add(jSeparator10);

        mnuPrincipales1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuPrincipales1.setText("Principales");
        mnuPrincipales1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrincipales1ActionPerformed(evt);
            }
        });
        menucontextual.add(mnuPrincipales1);

        mnuSecudarias1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuSecudarias1.setText("Secundarias");
        mnuSecudarias1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSecudarias1ActionPerformed(evt);
            }
        });
        menucontextual.add(mnuSecudarias1);

        mnuSeguridad1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        mnuSeguridad1.setText("Seguridad");
        mnuSeguridad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSeguridad1ActionPerformed(evt);
            }
        });
        menucontextual.add(mnuSeguridad1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        pnOficina1.setBackground(new java.awt.Color(153, 255, 255));
        pnOficina1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Oficina 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 51))); // NOI18N
        pnOficina1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chkLuzPrincipal1.setText("Luz Principal");
        chkLuzPrincipal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLuzPrincipal1ActionPerformed(evt);
            }
        });
        pnOficina1.add(chkLuzPrincipal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 40, -1, -1));

        chkLuzSecundaria1.setText("Luz Secundarial");
        chkLuzSecundaria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLuzSecundaria1ActionPerformed(evt);
            }
        });
        pnOficina1.add(chkLuzSecundaria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 87, -1, -1));

        chkLuzSeguridad1.setText("Luz Seguridadl");
        chkLuzSeguridad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLuzSeguridad1ActionPerformed(evt);
            }
        });
        pnOficina1.add(chkLuzSeguridad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 134, -1, -1));

        luz131.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programa/iconos/apagada2.jpg"))); // NOI18N
        pnOficina1.add(luz131, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 117, -1, -1));

        luz132.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programa/iconos/encendida2.jpg"))); // NOI18N
        pnOficina1.add(luz132, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        luz111.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programa/iconos/apagada2.jpg"))); // NOI18N
        pnOficina1.add(luz111, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        luz112.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programa/iconos/encendida2.jpg"))); // NOI18N
        pnOficina1.add(luz112, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        luz121.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programa/iconos/apagada2.jpg"))); // NOI18N
        pnOficina1.add(luz121, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        luz122.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programa/iconos/encendida2.jpg"))); // NOI18N
        pnOficina1.add(luz122, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        pnOficina2.setBackground(new java.awt.Color(255, 255, 204));
        pnOficina2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Oficina 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 0))); // NOI18N
        pnOficina2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chkLuzPrincipal2.setText("Luz Principal");
        chkLuzPrincipal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLuzPrincipal2ActionPerformed(evt);
            }
        });
        pnOficina2.add(chkLuzPrincipal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 44, -1, -1));

        chkLuzSecundaria2.setText("Luz Secundarial");
        chkLuzSecundaria2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLuzSecundaria2ActionPerformed(evt);
            }
        });
        pnOficina2.add(chkLuzSecundaria2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 91, -1, -1));

        chkLuzSeguridad2.setText("Luz Seguridadl");
        chkLuzSeguridad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLuzSeguridad2ActionPerformed(evt);
            }
        });
        pnOficina2.add(chkLuzSeguridad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 138, -1, -1));

        luz211.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programa/iconos/apagada2.jpg"))); // NOI18N
        pnOficina2.add(luz211, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        luz212.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programa/iconos/encendida2.jpg"))); // NOI18N
        pnOficina2.add(luz212, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        luz221.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programa/iconos/apagada2.jpg"))); // NOI18N
        pnOficina2.add(luz221, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        luz231.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programa/iconos/apagada2.jpg"))); // NOI18N
        pnOficina2.add(luz231, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        luz232.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programa/iconos/encendida2.jpg"))); // NOI18N
        pnOficina2.add(luz232, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        luz222.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programa/iconos/encendida2.jpg"))); // NOI18N
        pnOficina2.add(luz222, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        pnOficina3.setBackground(new java.awt.Color(204, 255, 204));
        pnOficina3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Oficina 3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 51))); // NOI18N
        pnOficina3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chkLuzPrincipal3.setText("Luz Principal");
        chkLuzPrincipal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLuzPrincipal3ActionPerformed(evt);
            }
        });
        pnOficina3.add(chkLuzPrincipal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 44, -1, -1));

        chkLuzSecundaria3.setText("Luz Secundarial");
        chkLuzSecundaria3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLuzSecundaria3ActionPerformed(evt);
            }
        });
        pnOficina3.add(chkLuzSecundaria3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 91, -1, -1));

        chkLuzSeguridad3.setText("Luz Seguridadl");
        chkLuzSeguridad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLuzSeguridad3ActionPerformed(evt);
            }
        });
        pnOficina3.add(chkLuzSeguridad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 138, -1, -1));

        luz321.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programa/iconos/apagada2.jpg"))); // NOI18N
        pnOficina3.add(luz321, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        luz311.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programa/iconos/apagada2.jpg"))); // NOI18N
        pnOficina3.add(luz311, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        luz312.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programa/iconos/encendida2.jpg"))); // NOI18N
        pnOficina3.add(luz312, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        luz322.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programa/iconos/encendida2.jpg"))); // NOI18N
        pnOficina3.add(luz322, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        luz331.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programa/iconos/apagada2.jpg"))); // NOI18N
        pnOficina3.add(luz331, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        luz332.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programa/iconos/encendida2.jpg"))); // NOI18N
        pnOficina3.add(luz332, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jToolBar1.setRollover(true);

        bapagartodas.setText("apagar todas");
        bapagartodas.setFocusable(false);
        bapagartodas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bapagartodas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bapagartodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bapagartodasActionPerformed(evt);
            }
        });
        jToolBar1.add(bapagartodas);

        bencendertodas.setText("encender todas");
        bencendertodas.setFocusable(false);
        bencendertodas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bencendertodas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bencendertodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bencendertodasActionPerformed(evt);
            }
        });
        jToolBar1.add(bencendertodas);
        jToolBar1.add(jSeparator6);

        bdia.setText("DIA");
        bdia.setFocusable(false);
        bdia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bdia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bdia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdiaActionPerformed(evt);
            }
        });
        jToolBar1.add(bdia);

        bnoche.setText("NOCHE");
        bnoche.setFocusable(false);
        bnoche.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bnoche.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bnoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnocheActionPerformed(evt);
            }
        });
        jToolBar1.add(bnoche);

        bdiaicono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programa/iconos/dia.png"))); // NOI18N
        bdiaicono.setFocusable(false);
        bdiaicono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bdiaicono.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bdiaicono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdiaiconoActionPerformed(evt);
            }
        });
        jToolBar1.add(bdiaicono);

        bnocheicono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programa/iconos/luna.png"))); // NOI18N
        bnocheicono.setFocusable(false);
        bnocheicono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bnocheicono.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bnocheicono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnocheiconoActionPerformed(evt);
            }
        });
        jToolBar1.add(bnocheicono);
        jToolBar1.add(jSeparator7);

        binfoprincipales.setText("info Principales");
        binfoprincipales.setFocusable(false);
        binfoprincipales.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        binfoprincipales.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        binfoprincipales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binfoprincipalesActionPerformed(evt);
            }
        });
        jToolBar1.add(binfoprincipales);

        binfosecundarias.setText("info Secundarias");
        binfosecundarias.setFocusable(false);
        binfosecundarias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        binfosecundarias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        binfosecundarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binfosecundariasActionPerformed(evt);
            }
        });
        jToolBar1.add(binfosecundarias);

        binfoseguridad.setText("info Seguridad");
        binfoseguridad.setFocusable(false);
        binfoseguridad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        binfoseguridad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        binfoseguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binfoseguridadActionPerformed(evt);
            }
        });
        jToolBar1.add(binfoseguridad);
        jToolBar1.add(jSeparator8);

        mnuActivación.setText("Activación");

        mnuApagarT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnuApagarT.setText("Apagar Todas");
        mnuApagarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuApagarTActionPerformed(evt);
            }
        });
        mnuActivación.add(mnuApagarT);

        mnuEncenderT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mnuEncenderT.setText("Encender Todas");
        mnuEncenderT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEncenderTActionPerformed(evt);
            }
        });
        mnuActivación.add(mnuEncenderT);
        mnuActivación.add(jSeparator1);

        mnuDia.setText("Dia");

        mnuOfD1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        mnuOfD1.setText("Oficina 1");
        mnuOfD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOfD1ActionPerformed(evt);
            }
        });
        mnuDia.add(mnuOfD1);

        mnuOfD2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        mnuOfD2.setText("Oficina 2");
        mnuOfD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOfD2ActionPerformed(evt);
            }
        });
        mnuDia.add(mnuOfD2);

        mnuOfD3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        mnuOfD3.setText("Oficina 3");
        mnuOfD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOfD3ActionPerformed(evt);
            }
        });
        mnuDia.add(mnuOfD3);
        mnuDia.add(jSeparator3);

        mnuTodasD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        mnuTodasD.setText("Todas");
        mnuTodasD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTodasDActionPerformed(evt);
            }
        });
        mnuDia.add(mnuTodasD);

        mnuActivación.add(mnuDia);

        mnuNoche.setText("Noche");

        mnuOfN1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_MASK));
        mnuOfN1.setText("Oficina 1");
        mnuOfN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOfN1ActionPerformed(evt);
            }
        });
        mnuNoche.add(mnuOfN1);

        mnuOfN2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_MASK));
        mnuOfN2.setText("Oficina 2");
        mnuOfN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOfN2ActionPerformed(evt);
            }
        });
        mnuNoche.add(mnuOfN2);

        mnuOfN3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.CTRL_MASK));
        mnuOfN3.setText("Oficina 3");
        mnuOfN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOfN3ActionPerformed(evt);
            }
        });
        mnuNoche.add(mnuOfN3);
        mnuNoche.add(jSeparator4);

        mnuTodasN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mnuTodasN.setText("Todas");
        mnuTodasN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTodasNActionPerformed(evt);
            }
        });
        mnuNoche.add(mnuTodasN);

        mnuActivación.add(mnuNoche);
        mnuActivación.add(jSeparator2);

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuActivación.add(mnuSalir);

        mnuBarraMenus.add(mnuActivación);

        mnuInfo.setText("Info");

        mnuPrincipales.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuPrincipales.setText("Principales");
        mnuPrincipales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrincipalesActionPerformed(evt);
            }
        });
        mnuInfo.add(mnuPrincipales);

        mnuSecudarias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuSecudarias.setText("Secundarias");
        mnuSecudarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSecudariasActionPerformed(evt);
            }
        });
        mnuInfo.add(mnuSecudarias);

        mnuSeguridad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        mnuSeguridad.setText("Seguridad");
        mnuSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSeguridadActionPerformed(evt);
            }
        });
        mnuInfo.add(mnuSeguridad);
        mnuInfo.add(jSeparator5);

        mnuAcerca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        mnuAcerca.setText("Acerca de...");
        mnuInfo.add(mnuAcerca);

        mnuBarraMenus.add(mnuInfo);

        setJMenuBar(mnuBarraMenus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(pnOficina1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnOficina2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnOficina3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnOficina2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnOficina3, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(pnOficina1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuOfD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOfD1ActionPerformed
        chkLuzPrincipal1.setSelected(true);
        chkLuzSecundaria1.setSelected(true);
        chkLuzSeguridad1.setSelected(false);
        luz111.setVisible(false);
        luz121.setVisible(false);
        luz131.setVisible(true);
        luz112.setVisible(true);
        luz122.setVisible(true);
        luz132.setVisible(false);
        // TODO add your handling code here:
                              
    }//GEN-LAST:event_mnuOfD1ActionPerformed

    private void mnuOfD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOfD2ActionPerformed
        chkLuzPrincipal2.setSelected(true);
        chkLuzSecundaria2.setSelected(true);
        chkLuzSeguridad2.setSelected(false);
        luz211.setVisible(false);
        luz221.setVisible(false);
        luz231.setVisible(true);
        luz212.setVisible(true);
        luz222.setVisible(true);
        luz232.setVisible(false);
    }//GEN-LAST:event_mnuOfD2ActionPerformed

    private void mnuOfD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOfD3ActionPerformed
        chkLuzPrincipal3.setSelected(true);
        chkLuzSecundaria3.setSelected(true);
        chkLuzSeguridad3.setSelected(false);
        luz311.setVisible(false);
        luz321.setVisible(false);
        luz331.setVisible(true);
        luz312.setVisible(true);
        luz322.setVisible(true);
        luz332.setVisible(false);
    }//GEN-LAST:event_mnuOfD3ActionPerformed

    private void mnuTodasDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTodasDActionPerformed
        mnuOfD1ActionPerformed(null);
        mnuOfD2ActionPerformed(null);
        mnuOfD3ActionPerformed(null);
        luz111.setVisible(false);
        luz121.setVisible(false);
        luz131.setVisible(true);
        luz211.setVisible(false);
        luz221.setVisible(false);
        luz231.setVisible(true);
        luz311.setVisible(false);
        luz321.setVisible(false);
        luz331.setVisible(true);
        luz112.setVisible(true);
        luz122.setVisible(true);
        luz132.setVisible(false);
        luz212.setVisible(true);
        luz222.setVisible(true);
        luz232.setVisible(false);
        luz312.setVisible(true);
        luz322.setVisible(true);
        luz332.setVisible(false);// TODO add your handling code here:
                               
    }//GEN-LAST:event_mnuTodasDActionPerformed

    private void mnuOfN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOfN1ActionPerformed
        chkLuzPrincipal1.setSelected(false);
        chkLuzSecundaria1.setSelected(false);
        chkLuzSeguridad1.setSelected(true);
        luz111.setVisible(true);
        luz121.setVisible(true);
        luz131.setVisible(false);
        
        luz112.setVisible(false);
        luz122.setVisible(false);
        luz132.setVisible(true);
       
    }//GEN-LAST:event_mnuOfN1ActionPerformed

    private void mnuOfN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOfN2ActionPerformed
        chkLuzPrincipal2.setSelected(false);
        chkLuzSecundaria2.setSelected(false);
        chkLuzSeguridad2.setSelected(true);
        luz211.setVisible(true);
        luz221.setVisible(true);
        luz231.setVisible(false);
        luz212.setVisible(false);
        luz222.setVisible(false);
        luz232.setVisible(true);
        
    }//GEN-LAST:event_mnuOfN2ActionPerformed

    private void mnuOfN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOfN3ActionPerformed
        chkLuzPrincipal3.setSelected(false);
        chkLuzSecundaria3.setSelected(false);
        chkLuzSeguridad3.setSelected(true);
        
         luz111.setVisible(true);
        luz121.setVisible(true);
        luz131.setVisible(false);
        luz211.setVisible(true);
        luz221.setVisible(true);
        luz231.setVisible(false);
        luz311.setVisible(true);
        luz321.setVisible(true);
        luz331.setVisible(false);
        luz112.setVisible(false);
        luz122.setVisible(false);
        luz132.setVisible(true);
        luz212.setVisible(false);
        luz222.setVisible(false);
        luz232.setVisible(true);
        luz312.setVisible(false);
        luz322.setVisible(false);
        luz332.setVisible(true);
        
    }//GEN-LAST:event_mnuOfN3ActionPerformed

    private void mnuTodasNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTodasNActionPerformed
        mnuOfN1ActionPerformed(null);
        mnuOfN2ActionPerformed(null);
        mnuOfN3ActionPerformed(null);
        
        luz311.setVisible(true);
        luz321.setVisible(true);
        luz331.setVisible(false);
        
        luz312.setVisible(false);
        luz322.setVisible(false);
        luz332.setVisible(true);
    }//GEN-LAST:event_mnuTodasNActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        dispose();
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuApagarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuApagarTActionPerformed
        chkLuzPrincipal1.setSelected(false);
        chkLuzSecundaria1.setSelected(false);
        chkLuzSeguridad1.setSelected(false);
        chkLuzPrincipal2.setSelected(false);
        chkLuzSecundaria2.setSelected(false);
        chkLuzSeguridad2.setSelected(false);
        chkLuzPrincipal3.setSelected(false);
        chkLuzSecundaria3.setSelected(false);
        chkLuzSeguridad3.setSelected(false);
        luz111.setVisible(true);
        luz121.setVisible(true);
        luz131.setVisible(true);
        luz211.setVisible(true);
        luz221.setVisible(true);
        luz231.setVisible(true);
        luz311.setVisible(true);
        luz321.setVisible(true);
        luz331.setVisible(true);
        luz112.setVisible(false);
        luz122.setVisible(false);
        luz132.setVisible(false);
        luz212.setVisible(false);
        luz222.setVisible(false);
        luz232.setVisible(false);
        luz312.setVisible(false);
        luz322.setVisible(false);
        luz332.setVisible(false);
        
    }//GEN-LAST:event_mnuApagarTActionPerformed

    private void mnuEncenderTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEncenderTActionPerformed
        chkLuzPrincipal1.setSelected(true);
        chkLuzSecundaria1.setSelected(true);
        chkLuzSeguridad1.setSelected(true);
        chkLuzPrincipal2.setSelected(true);
        chkLuzSecundaria2.setSelected(true);
        chkLuzSeguridad2.setSelected(true);
        chkLuzPrincipal3.setSelected(true);
        chkLuzSecundaria3.setSelected(true);
        chkLuzSeguridad3.setSelected(true);
        luz112.setVisible(true);
        luz122.setVisible(true);
        luz132.setVisible(true);
        luz212.setVisible(true);
        luz222.setVisible(true);
        luz232.setVisible(true);
        luz312.setVisible(true);
        luz322.setVisible(true);
        luz332.setVisible(true);
        luz111.setVisible(false);
        luz121.setVisible(false);
        luz131.setVisible(false);
        luz211.setVisible(false);
        luz221.setVisible(false);
        luz231.setVisible(false);
        luz311.setVisible(false);
        luz321.setVisible(false);
        luz331.setVisible(false);
    }//GEN-LAST:event_mnuEncenderTActionPerformed

    private void mnuPrincipalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrincipalesActionPerformed
        int luces=0;
        if(chkLuzPrincipal1.isSelected())
            luces++;
        if(chkLuzPrincipal2.isSelected())
            luces++;
        if(chkLuzPrincipal3.isSelected())
            luces++;
        JOptionPane.showConfirmDialog(this, "Hay "+ luces+" encendidas y "+(3-luces)+" apagadas", "PRINCIPALES", 0);
    }//GEN-LAST:event_mnuPrincipalesActionPerformed

    private void mnuSecudariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSecudariasActionPerformed
        int luces=0;
        if(chkLuzSecundaria1.isSelected())
            luces++;
        if(chkLuzSecundaria2.isSelected())
            luces++;
        if(chkLuzSecundaria3.isSelected())
            luces++;
        JOptionPane.showConfirmDialog(this, "Hay "+ luces+" encendidas y "+(3-luces)+" apagadas", "SECUNDARIAS", 0);
    }//GEN-LAST:event_mnuSecudariasActionPerformed

    private void mnuSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSeguridadActionPerformed
        int luces=0;
        if(chkLuzSeguridad1.isSelected())
            luces++;
        if(chkLuzSeguridad2.isSelected())
            luces++;
        if(chkLuzSeguridad3.isSelected())
            luces++;
        JOptionPane.showConfirmDialog(this, "Hay "+ luces+" encendidas y "+(3-luces)+" apagadas", "SEGURIDAD", 0);
    }//GEN-LAST:event_mnuSeguridadActionPerformed

    private void bapagartodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bapagartodasActionPerformed
        chkLuzPrincipal1.setSelected(false); 
        chkLuzSecundaria1.setSelected(false); 
        chkLuzSeguridad1.setSelected(false); 
        chkLuzPrincipal2.setSelected(false); 
        chkLuzSecundaria2.setSelected(false); 
        chkLuzSeguridad2.setSelected(false); 
        chkLuzPrincipal3.setSelected(false); 
        chkLuzSecundaria3.setSelected(false); 
        chkLuzSeguridad3.setSelected(false);  
        luz111.setVisible(true);
        luz121.setVisible(true);
        luz131.setVisible(true);
        luz211.setVisible(true);
        luz221.setVisible(true);
        luz231.setVisible(true);
        luz311.setVisible(true);
        luz321.setVisible(true);
        luz331.setVisible(true);
        luz112.setVisible(false);
        luz122.setVisible(false);
        luz132.setVisible(false);
        luz212.setVisible(false);
        luz222.setVisible(false);
        luz232.setVisible(false);
        luz312.setVisible(false);
        luz322.setVisible(false);
        luz332.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_bapagartodasActionPerformed

    private void bencendertodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bencendertodasActionPerformed

        chkLuzPrincipal1.setSelected(true);
        chkLuzSecundaria1.setSelected(true);
        chkLuzSeguridad1.setSelected(true);
        chkLuzPrincipal2.setSelected(true);
        chkLuzSecundaria2.setSelected(true);
        chkLuzSeguridad2.setSelected(true);
        chkLuzPrincipal3.setSelected(true);
        chkLuzSecundaria3.setSelected(true);
        chkLuzSeguridad3.setSelected(true);
        luz112.setVisible(true);
        luz122.setVisible(true);
        luz132.setVisible(true);
        luz212.setVisible(true);
        luz222.setVisible(true);
        luz232.setVisible(true);
        luz312.setVisible(true);
        luz322.setVisible(true);
        luz332.setVisible(true);
        luz111.setVisible(false);
        luz121.setVisible(false);
        luz131.setVisible(false);
        luz211.setVisible(false);
        luz221.setVisible(false);
        luz231.setVisible(false);
        luz311.setVisible(false);
        luz321.setVisible(false);
        luz331.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_bencendertodasActionPerformed

    private void bdiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdiaActionPerformed
        mnuOfD1ActionPerformed(null);
        mnuOfD2ActionPerformed(null);
        mnuOfD3ActionPerformed(null);
        luz111.setVisible(false);
        luz121.setVisible(false);
        luz131.setVisible(true);
        luz211.setVisible(false);
        luz221.setVisible(false);
        luz231.setVisible(true);
        luz311.setVisible(false);
        luz321.setVisible(false);
        luz331.setVisible(true);
        luz112.setVisible(true);
        luz122.setVisible(true);
        luz132.setVisible(false);
        luz212.setVisible(true);
        luz222.setVisible(true);
        luz232.setVisible(false);
        luz312.setVisible(true);
        luz322.setVisible(true);
        luz332.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_bdiaActionPerformed

    private void bnocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnocheActionPerformed
        mnuOfN1ActionPerformed(null);
        mnuOfN2ActionPerformed(null);
        mnuOfN3ActionPerformed(null);
        luz111.setVisible(true);
        luz121.setVisible(true);
        luz131.setVisible(false);
        luz211.setVisible(true);
        luz221.setVisible(true);
        luz231.setVisible(false);
        luz311.setVisible(true);
        luz321.setVisible(true);
        luz331.setVisible(false);
        luz112.setVisible(false);
        luz122.setVisible(false);
        luz132.setVisible(true);
        luz212.setVisible(false);
        luz222.setVisible(false);
        luz232.setVisible(true);
        luz312.setVisible(false);
        luz322.setVisible(false);
        luz332.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_bnocheActionPerformed

    private void bdiaiconoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdiaiconoActionPerformed
        mnuOfD1ActionPerformed(null);
        mnuOfD2ActionPerformed(null);
        mnuOfD3ActionPerformed(null);
        luz111.setVisible(false);
        luz121.setVisible(false);
        luz131.setVisible(true);
        luz211.setVisible(false);
        luz221.setVisible(false);
        luz231.setVisible(true);
        luz311.setVisible(false);
        luz321.setVisible(false);
        luz331.setVisible(true);
        luz112.setVisible(true);
        luz122.setVisible(true);
        luz132.setVisible(false);
        luz212.setVisible(true);
        luz222.setVisible(true);
        luz232.setVisible(false);
        luz312.setVisible(true);
        luz322.setVisible(true);
        luz332.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_bdiaiconoActionPerformed

    private void bnocheiconoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnocheiconoActionPerformed
        mnuOfN1ActionPerformed(null);
        mnuOfN2ActionPerformed(null);
        mnuOfN3ActionPerformed(null); 
        luz111.setVisible(true);
        luz121.setVisible(true);
        luz131.setVisible(false);
        luz211.setVisible(true);
        luz221.setVisible(true);
        luz231.setVisible(false);
        luz311.setVisible(true);
        luz321.setVisible(true);
        luz331.setVisible(false);
        luz112.setVisible(false);
        luz122.setVisible(false);
        luz132.setVisible(true);
        luz212.setVisible(false);
        luz222.setVisible(false);
        luz232.setVisible(true);
        luz312.setVisible(false);
        luz322.setVisible(false);
        luz332.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_bnocheiconoActionPerformed

    private void binfoprincipalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binfoprincipalesActionPerformed
int luces=0;
        if(chkLuzPrincipal1.isSelected())
            luces++;
        if(chkLuzPrincipal2.isSelected())
            luces++;
        if(chkLuzPrincipal3.isSelected())
            luces++;
        JOptionPane.showConfirmDialog(this, "Hay "+ luces+" encendidas y "+(3-luces)+" apagadas", "PRINCIPALES", 0);        // TODO add your handling code here:
    }//GEN-LAST:event_binfoprincipalesActionPerformed

    private void binfosecundariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binfosecundariasActionPerformed
int luces=0;
        if(chkLuzSecundaria1.isSelected())
            luces++;
        if(chkLuzSecundaria2.isSelected())
            luces++;
        if(chkLuzSecundaria3.isSelected())
            luces++;
        JOptionPane.showConfirmDialog(this, "Hay "+ luces+" encendidas y "+(3-luces)+" apagadas", "SECUNDARIAS", 0);        // TODO add your handling code here:
    }//GEN-LAST:event_binfosecundariasActionPerformed

    private void binfoseguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binfoseguridadActionPerformed
int luces=0;
        if(chkLuzSeguridad1.isSelected())
            luces++;
        if(chkLuzSeguridad2.isSelected())
            luces++;
        if(chkLuzSeguridad3.isSelected())
            luces++;
        JOptionPane.showConfirmDialog(this, "Hay "+ luces+" encendidas y "+(3-luces)+" apagadas", "SEGURIDAD", 0);        // TODO add your handling code here:
    }//GEN-LAST:event_binfoseguridadActionPerformed

    private void mnuApagarT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuApagarT1ActionPerformed
 chkLuzPrincipal1.setSelected(false); 
        chkLuzSecundaria1.setSelected(false); 
        chkLuzSeguridad1.setSelected(false); 
        chkLuzPrincipal2.setSelected(false); 
        chkLuzSecundaria2.setSelected(false); 
        chkLuzSeguridad2.setSelected(false); 
        chkLuzPrincipal3.setSelected(false); 
        chkLuzSecundaria3.setSelected(false); 
        chkLuzSeguridad3.setSelected(false);
        luz111.setVisible(true);
        luz121.setVisible(true);
        luz131.setVisible(true);
        luz211.setVisible(true);
        luz221.setVisible(true);
        luz231.setVisible(true);
        luz311.setVisible(true);
        luz321.setVisible(true);
        luz331.setVisible(true);
        luz112.setVisible(false);
        luz122.setVisible(false);
        luz132.setVisible(false);
        luz212.setVisible(false);
        luz222.setVisible(false);
        luz232.setVisible(false);
        luz312.setVisible(false);
        luz322.setVisible(false);
        luz332.setVisible(false);// TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_mnuApagarT1ActionPerformed

    private void mnuEncenderT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEncenderT1ActionPerformed
        chkLuzPrincipal1.setSelected(true);
        chkLuzSecundaria1.setSelected(true);
        chkLuzSeguridad1.setSelected(true);
        chkLuzPrincipal2.setSelected(true);
        chkLuzSecundaria2.setSelected(true);
        chkLuzSeguridad2.setSelected(true);
        chkLuzPrincipal3.setSelected(true);
        chkLuzSecundaria3.setSelected(true);
        chkLuzSeguridad3.setSelected(true);
        luz112.setVisible(true);
        luz122.setVisible(true);
        luz132.setVisible(true);
        luz212.setVisible(true);
        luz222.setVisible(true);
        luz232.setVisible(true);
        luz312.setVisible(true);
        luz322.setVisible(true);
        luz332.setVisible(true);
        luz111.setVisible(false);
        luz121.setVisible(false);
        luz131.setVisible(false);
        luz211.setVisible(false);
        luz221.setVisible(false);
        luz231.setVisible(false);
        luz311.setVisible(false);
        luz321.setVisible(false);
        luz331.setVisible(false);


// T
// TODO add your handling code here:
    }//GEN-LAST:event_mnuEncenderT1ActionPerformed

    private void mnuPrincipales1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrincipales1ActionPerformed
        int luces=0;
        if(chkLuzPrincipal1.isSelected())
            luces++;
        if(chkLuzPrincipal2.isSelected())
            luces++;
        if(chkLuzPrincipal3.isSelected())
            luces++;
        JOptionPane.showConfirmDialog(this, "Hay "+ luces+" encendidas y "+(3-luces)+" apagadas", "PRINCIPALES", 0);        // TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_mnuPrincipales1ActionPerformed

    private void mnuSeguridad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSeguridad1ActionPerformed
        int luces=0;
        if(chkLuzSeguridad1.isSelected())
            luces++;
        if(chkLuzSeguridad2.isSelected())
            luces++;
        if(chkLuzSeguridad3.isSelected())
            luces++;
        JOptionPane.showConfirmDialog(this, "Hay "+ luces+" encendidas y "+(3-luces)+" apagadas", "SEGURIDAD", 0);        // TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_mnuSeguridad1ActionPerformed

    private void mnuSecudarias1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSecudarias1ActionPerformed
                                            
int luces=0;
        if(chkLuzSecundaria1.isSelected())
            luces++;
        if(chkLuzSecundaria2.isSelected())
            luces++;
        if(chkLuzSecundaria3.isSelected())
            luces++;
        JOptionPane.showConfirmDialog(this, "Hay "+ luces+" encendidas y "+(3-luces)+" apagadas", "SECUNDARIAS", 0);        // TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_mnuSecudarias1ActionPerformed

    private void menucontextualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menucontextualMouseClicked

// TODO add your handling code here:
    }//GEN-LAST:event_menucontextualMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

if(evt.getButton()==3){
        menucontextual.show(this, evt.getX(), evt.getY());
}// TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void mnuTodasN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTodasN1ActionPerformed
 mnuOfN1ActionPerformed(null);
        mnuOfN2ActionPerformed(null);
        mnuOfN3ActionPerformed(null);
        luz111.setVisible(true);
        luz121.setVisible(true);
        luz131.setVisible(false);
        luz211.setVisible(true);
        luz221.setVisible(true);
        luz231.setVisible(false);
        luz311.setVisible(true);
        luz321.setVisible(true);
        luz331.setVisible(false);
        luz112.setVisible(false);
        luz122.setVisible(false);
        luz132.setVisible(true);
        luz212.setVisible(false);
        luz222.setVisible(false);
        luz232.setVisible(true);
        luz312.setVisible(false);
        luz322.setVisible(false);
        luz332.setVisible(true);
        
        
                // TODO add your handling code here:
    }//GEN-LAST:event_mnuTodasN1ActionPerformed

    private void mnuTodasD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTodasD1ActionPerformed
        mnuOfD1ActionPerformed(null);
        mnuOfD2ActionPerformed(null);
        mnuOfD3ActionPerformed(null);
        luz111.setVisible(false);
        luz121.setVisible(false);
        luz131.setVisible(true);
        luz211.setVisible(false);
        luz221.setVisible(false);
        luz231.setVisible(true);
        luz311.setVisible(false);
        luz321.setVisible(false);
        luz331.setVisible(true);
        luz112.setVisible(true);
        luz122.setVisible(true);
        luz132.setVisible(false);
        luz212.setVisible(true);
        luz222.setVisible(true);
        luz232.setVisible(false);
        luz312.setVisible(true);
        luz322.setVisible(true);
        luz332.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_mnuTodasD1ActionPerformed

    private void chkLuzPrincipal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLuzPrincipal1ActionPerformed
if(chkLuzPrincipal1.isSelected()==true){
luz111.setVisible(false);
luz112.setVisible(true);
chkLuzSeguridad1.setSelected(false);
luz131.setVisible(true);
luz132.setVisible(false);
}else{
luz111.setVisible(true);
luz112.setVisible(false);
}

        
// TODO add your handling code here:
    }//GEN-LAST:event_chkLuzPrincipal1ActionPerformed

    private void chkLuzSecundaria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLuzSecundaria1ActionPerformed
if(chkLuzSecundaria1.isSelected()==true){
luz121.setVisible(false);
luz122.setVisible(true);
chkLuzSeguridad1.setSelected(false);
luz131.setVisible(true);
luz132.setVisible(false);
}else{
luz121.setVisible(true);
luz122.setVisible(false);
}        // TODO add your handling code here:
    }//GEN-LAST:event_chkLuzSecundaria1ActionPerformed

    private void chkLuzSeguridad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLuzSeguridad1ActionPerformed
if(chkLuzSeguridad1.isSelected()==true){
luz131.setVisible(false);
luz132.setVisible(true);
chkLuzSecundaria1.setSelected(false);
chkLuzPrincipal1.setSelected(false);
luz121.setVisible(true);
luz122.setVisible(false);
luz111.setVisible(true);
luz112.setVisible(false);
}else{
luz131.setVisible(true);
luz132.setVisible(false);

}        



    }//GEN-LAST:event_chkLuzSeguridad1ActionPerformed

    private void chkLuzPrincipal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLuzPrincipal2ActionPerformed
if(chkLuzPrincipal2.isSelected()==true){
luz211.setVisible(false);
luz212.setVisible(true);
chkLuzSeguridad2.setSelected(false);
luz231.setVisible(true);
luz232.setVisible(false);
}else{
luz211.setVisible(true);
luz212.setVisible(false);
}        // TODO add your handling code here:
    }//GEN-LAST:event_chkLuzPrincipal2ActionPerformed

    private void chkLuzSecundaria2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLuzSecundaria2ActionPerformed
if(chkLuzSecundaria2.isSelected()==true){
luz221.setVisible(false);
luz222.setVisible(true);
chkLuzSeguridad2.setSelected(false);
luz231.setVisible(true);
luz232.setVisible(false);
}else{
luz221.setVisible(true);
luz222.setVisible(false);
}         // TODO add your handling code here:
    }//GEN-LAST:event_chkLuzSecundaria2ActionPerformed

    private void chkLuzSeguridad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLuzSeguridad2ActionPerformed
if(chkLuzSeguridad2.isSelected()==true){
luz231.setVisible(false);
luz232.setVisible(true);
chkLuzSecundaria2.setSelected(false);
chkLuzPrincipal2.setSelected(false);
luz221.setVisible(true);
luz222.setVisible(false);
luz211.setVisible(true);
luz212.setVisible(false);
}else{
luz231.setVisible(true);
luz232.setVisible(false);

}              // TODO add your handling code here:
    }//GEN-LAST:event_chkLuzSeguridad2ActionPerformed

    private void chkLuzPrincipal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLuzPrincipal3ActionPerformed
if(chkLuzPrincipal3.isSelected()==true){
luz311.setVisible(false);
luz312.setVisible(true);
chkLuzSeguridad3.setSelected(false);
luz331.setVisible(true);
luz332.setVisible(false);
}else{
luz311.setVisible(true);
luz312.setVisible(false);
}          // TODO add your handling code here:
    }//GEN-LAST:event_chkLuzPrincipal3ActionPerformed

    private void chkLuzSecundaria3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLuzSecundaria3ActionPerformed
if(chkLuzSecundaria3.isSelected()==true){
luz321.setVisible(false);
luz322.setVisible(true);
chkLuzSeguridad3.setSelected(false);
luz331.setVisible(true);
luz332.setVisible(false);
}else{
luz321.setVisible(true);
luz322.setVisible(false);
}         // TODO add your handling code here:
    }//GEN-LAST:event_chkLuzSecundaria3ActionPerformed

    private void chkLuzSeguridad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLuzSeguridad3ActionPerformed
if(chkLuzSeguridad3.isSelected()==true){
luz331.setVisible(false);
luz332.setVisible(true);
chkLuzSecundaria3.setSelected(false);
chkLuzPrincipal3.setSelected(false);
luz321.setVisible(true);
luz322.setVisible(false);
luz311.setVisible(true);
luz312.setVisible(false);
}else{
luz331.setVisible(true);
luz332.setVisible(false);

}         // TODO add your handling code here:
    }//GEN-LAST:event_chkLuzSeguridad3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bapagartodas;
    private javax.swing.JButton bdia;
    private javax.swing.JButton bdiaicono;
    private javax.swing.JButton bencendertodas;
    private javax.swing.JButton binfoprincipales;
    private javax.swing.JButton binfosecundarias;
    private javax.swing.JButton binfoseguridad;
    private javax.swing.JButton bnoche;
    private javax.swing.JButton bnocheicono;
    private javax.swing.JCheckBox chkLuzPrincipal1;
    private javax.swing.JCheckBox chkLuzPrincipal2;
    private javax.swing.JCheckBox chkLuzPrincipal3;
    private javax.swing.JCheckBox chkLuzSecundaria1;
    private javax.swing.JCheckBox chkLuzSecundaria2;
    private javax.swing.JCheckBox chkLuzSecundaria3;
    private javax.swing.JCheckBox chkLuzSeguridad1;
    private javax.swing.JCheckBox chkLuzSeguridad2;
    private javax.swing.JCheckBox chkLuzSeguridad3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel luz111;
    private javax.swing.JLabel luz112;
    private javax.swing.JLabel luz121;
    private javax.swing.JLabel luz122;
    private javax.swing.JLabel luz131;
    private javax.swing.JLabel luz132;
    private javax.swing.JLabel luz211;
    private javax.swing.JLabel luz212;
    private javax.swing.JLabel luz221;
    private javax.swing.JLabel luz222;
    private javax.swing.JLabel luz231;
    private javax.swing.JLabel luz232;
    private javax.swing.JLabel luz311;
    private javax.swing.JLabel luz312;
    private javax.swing.JLabel luz321;
    private javax.swing.JLabel luz322;
    private javax.swing.JLabel luz331;
    private javax.swing.JLabel luz332;
    private javax.swing.JPopupMenu menucontextual;
    private javax.swing.JMenuItem mnuAcerca;
    private javax.swing.JMenu mnuActivación;
    private javax.swing.JMenuItem mnuApagarT;
    private javax.swing.JMenuItem mnuApagarT1;
    private javax.swing.JMenuBar mnuBarraMenus;
    private javax.swing.JMenu mnuDia;
    private javax.swing.JMenuItem mnuEncenderT;
    private javax.swing.JMenuItem mnuEncenderT1;
    private javax.swing.JMenu mnuInfo;
    private javax.swing.JMenu mnuNoche;
    private javax.swing.JMenuItem mnuOfD1;
    private javax.swing.JMenuItem mnuOfD2;
    private javax.swing.JMenuItem mnuOfD3;
    private javax.swing.JMenuItem mnuOfN1;
    private javax.swing.JMenuItem mnuOfN2;
    private javax.swing.JMenuItem mnuOfN3;
    private javax.swing.JMenuItem mnuPrincipales;
    private javax.swing.JMenuItem mnuPrincipales1;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenuItem mnuSecudarias;
    private javax.swing.JMenuItem mnuSecudarias1;
    private javax.swing.JMenuItem mnuSeguridad;
    private javax.swing.JMenuItem mnuSeguridad1;
    private javax.swing.JMenuItem mnuTodasD;
    private javax.swing.JMenuItem mnuTodasD1;
    private javax.swing.JMenuItem mnuTodasN;
    private javax.swing.JMenuItem mnuTodasN1;
    private javax.swing.JPanel pnOficina1;
    private javax.swing.JPanel pnOficina2;
    private javax.swing.JPanel pnOficina3;
    // End of variables declaration//GEN-END:variables
}
